version: '3'

services: 
  bakcend:
    build: 
      context: .
      dockerfile: ./nodejs/Dockerfile
    working_dir: /app
    volumes: 
      - ./../backend/package.json:/app/package.json
      - ./../backend/src:/app/src
    ports: 
      - ${PORT_NODE}:3001
    command: ${COMMAND_NODE}